# Generated by Django 4.2.21 on 2025-05-19 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lucid_bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lucidbank",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="saman",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
