# Generated by Django 4.2.21 on 2025-05-20 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lucid_bank", "0007_alter_lucidbank_date_alter_saman_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lucidbank",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 20, 14, 3, 12, 507150, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="saman",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 20, 14, 3, 12, 507150, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
