# Generated by Django 4.2.21 on 2025-05-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lucid_bank", "0010_balance"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Balance",
            new_name="AccountBalance",
        ),
    ]
