# Generated by Django 4.2.21 on 2025-05-29 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lucid_bank", "0011_rename_balance_accountbalance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountbalance",
            options={
                "verbose_name": "Balance Owed",
                "verbose_name_plural": "Balances owed",
            },
        ),
        migrations.RemoveField(
            model_name="accountbalance",
            name="actual_amount",
        ),
        migrations.RemoveField(
            model_name="accountbalance",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="accountbalance",
            name="actual_balance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The actual amount owed by suppliers",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountbalance",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The total VAT amount owed by suppliers",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountbalance",
            name="credit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="accountbalance",
            name="date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="accountbalance",
            name="debit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="accountbalance",
            name="transaction",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
