# Generated by Django 4.2.21 on 2025-05-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lucidapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Balance",
        ),
    ]
