# Generated by Django 4.2.21 on 2025-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SaOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("adendorff", "Adendorff"),
                            ("chemvulc", "Chemvulc"),
                            ("academy", "Academy"),
                            ("tools_wholesale", "Tools Wholesale"),
                            ("resolute_supplies", "Resolute Supplies"),
                            ("other", "Other"),
                        ],
                        default="n/a",
                        max_length=50,
                    ),
                ),
                (
                    "other_company",
                    models.CharField(
                        blank=True,
                        help_text="Only fill this if 'Other' is selected",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("zar_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "my_zar_rate",
                    models.FloatField(help_text="The ZAR rate for the order"),
                ),
                (
                    "client_rate",
                    models.FloatField(help_text="The client rate for the order"),
                ),
                ("usd_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("markup", models.FloatField(blank=True, default=32.0)),
                ("pick_up_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transport_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("delivery_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "internal_bank_deduction",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("revenue_vat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("profit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SA Order",
                "verbose_name_plural": "SA Orders",
            },
        ),
    ]
