# Generated by Django 4.2.21 on 2025-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sa_orders",
            "0002_remove_saorder_company_remove_saorder_other_company_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="saorder",
            name="transport_cost_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="The rate used to convert transport cost from USD to ZAR",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="saorder",
            name="client_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The conversion rate given to the client",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="saorder",
            name="markup",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=32.0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="saorder",
            name="my_zar_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The ZAR rate for USD conversion",
                max_digits=10,
            ),
        ),
    ]
