# Generated by Django 4.2.21 on 2025-05-19 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sa_orders", "0003_saorder_transport_cost_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingSAOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order_delivered",
                    models.BooleanField(
                        default=False, help_text="Has the order been delivered?"
                    ),
                ),
                (
                    "amount_owed",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount owed for the order",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "sa_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_order",
                        to="sa_orders.saorder",
                    ),
                ),
            ],
        ),
    ]
