# Generated by Django 4.2.21 on 2025-05-19 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sa_orders", "0004_pendingsaorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingsaorder",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="saorder",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
