# Generated by Django 4.2.21 on 2025-05-20 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sa_orders", "0005_alter_pendingsaorder_date_alter_saorder_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingsaorder",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="saorder",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
