# Generated by Django 4.2.21 on 2025-05-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The cost of the order in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "markup",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=17.5, max_digits=10
                    ),
                ),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("revenue_vat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("profit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
