# Generated by Django 4.2.21 on 2025-05-20 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("local_orders", "0002_alter_localorder_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localorder",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
