# Generated by Django 4.2.21 on 2025-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local_orders", "0003_alter_localorder_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="localorder",
            name="order_delivered",
            field=models.BooleanField(
                default=False, help_text="Has the order been delivered?"
            ),
        ),
    ]
